// AUTO-GENERATED by ExportPolytopes — do not edit manually.
static class PolytopeData_16Cell
{
    public static readonly double[][] verts = {
        new double[]{1, 0, 0, 0},
        new double[]{-1, 0, 0, 0},
        new double[]{0, 1, 0, 0},
        new double[]{0, -1, 0, 0},
        new double[]{0, 0, 1, 0},
        new double[]{0, 0, -1, 0},
        new double[]{0, 0, 0, 1},
        new double[]{0, 0, 0, -1},
    };
    public static readonly int[][] edges = {
        new int[]{0, 2},
        new int[]{0, 3},
        new int[]{0, 4},
        new int[]{0, 5},
        new int[]{0, 6},
        new int[]{0, 7},
        new int[]{1, 2},
        new int[]{1, 3},
        new int[]{1, 4},
        new int[]{1, 5},
        new int[]{1, 6},
        new int[]{1, 7},
        new int[]{2, 4},
        new int[]{2, 5},
        new int[]{2, 6},
        new int[]{2, 7},
        new int[]{3, 4},
        new int[]{3, 5},
        new int[]{3, 6},
        new int[]{3, 7},
        new int[]{4, 6},
        new int[]{4, 7},
        new int[]{5, 6},
        new int[]{5, 7},
    };
    public static readonly int[][][] cells = {
        new int[][] {
            new int[]{1, 2, 5, 7},
        },
        new int[][] {
            new int[]{7, 2, 5, 0},
        },
        new int[][] {
            new int[]{7, 3, 5, 1},
        },
        new int[][] {
            new int[]{0, 3, 5, 7},
        },
        new int[][] {
            new int[]{6, 2, 5, 1},
        },
        new int[][] {
            new int[]{0, 2, 5, 6},
        },
        new int[][] {
            new int[]{1, 3, 5, 6},
        },
        new int[][] {
            new int[]{6, 3, 5, 0},
        },
        new int[][] {
            new int[]{7, 2, 4, 1},
        },
        new int[][] {
            new int[]{0, 2, 4, 7},
        },
        new int[][] {
            new int[]{1, 3, 4, 7},
        },
        new int[][] {
            new int[]{7, 3, 4, 0},
        },
        new int[][] {
            new int[]{1, 2, 4, 6},
        },
        new int[][] {
            new int[]{6, 2, 4, 0},
        },
        new int[][] {
            new int[]{6, 3, 4, 1},
        },
        new int[][] {
            new int[]{0, 3, 4, 6},
        },
    };
    public static readonly double[][] normals = {
        new double[]{-0.5, 0.5, -0.5, -0.5},
        new double[]{0.5, 0.5, -0.5, -0.5},
        new double[]{-0.5, -0.5, -0.5, -0.5},
        new double[]{0.5, -0.5, -0.5, -0.5},
        new double[]{-0.5, 0.5, -0.5, 0.5},
        new double[]{0.5, 0.5, -0.5, 0.5},
        new double[]{-0.5, -0.5, -0.5, 0.5},
        new double[]{0.5, -0.5, -0.5, 0.5},
        new double[]{-0.5, 0.5, 0.5, -0.5},
        new double[]{0.5, 0.5, 0.5, -0.5},
        new double[]{-0.5, -0.5, 0.5, -0.5},
        new double[]{0.5, -0.5, 0.5, -0.5},
        new double[]{-0.5, 0.5, 0.5, 0.5},
        new double[]{0.5, 0.5, 0.5, 0.5},
        new double[]{-0.5, -0.5, 0.5, 0.5},
        new double[]{0.5, -0.5, 0.5, 0.5},
    };
}
