// Coordinator — maps polytope names to auto-generated static data classes.
// Data classes are regenerated by ExportPolytopes; this file is hand-written.
using System.Collections.Generic;

public static class PolytopeData
{
    public struct Entry
    {
        public double[][]  verts;
        public int[][]     edges;
        public int[][][]   cells;   // cells[ci][ti] = int[4] tetrahedron
        public double[][]  normals;
    }

    static readonly Dictionary<string, Entry> _all = new Dictionary<string, Entry>
    {
        ["5-cell"]   = new Entry { verts = PolytopeData_5Cell.verts,   edges = PolytopeData_5Cell.edges,   cells = PolytopeData_5Cell.cells,   normals = PolytopeData_5Cell.normals   },
        ["8-cell"]   = new Entry { verts = PolytopeData_8Cell.verts,   edges = PolytopeData_8Cell.edges,   cells = PolytopeData_8Cell.cells,   normals = PolytopeData_8Cell.normals   },
        ["16-cell"]  = new Entry { verts = PolytopeData_16Cell.verts,  edges = PolytopeData_16Cell.edges,  cells = PolytopeData_16Cell.cells,  normals = PolytopeData_16Cell.normals  },
        ["24-cell"]  = new Entry { verts = PolytopeData_24Cell.verts,  edges = PolytopeData_24Cell.edges,  cells = PolytopeData_24Cell.cells,  normals = PolytopeData_24Cell.normals  },
        ["600-cell"] = new Entry { verts = PolytopeData_600Cell.verts, edges = PolytopeData_600Cell.edges, cells = PolytopeData_600Cell.cells, normals = PolytopeData_600Cell.normals },
        ["120-cell"] = new Entry { verts = PolytopeData_120Cell.verts, edges = PolytopeData_120Cell.edges, cells = PolytopeData_120Cell.cells, normals = PolytopeData_120Cell.normals },
    };

    public static Entry Get(string name)
    {
        if (_all.TryGetValue(name, out var e)) return e;
        throw new System.ArgumentException("Unknown polytope: " + name);
    }
}
