// AUTO-GENERATED by ExportPolytopes — do not edit manually.
static class PolytopeData_5Cell
{
    public static readonly double[][] verts = {
        new double[]{1, 1, 1, -0.4472136},
        new double[]{-1, 1, -1, -0.4472136},
        new double[]{1, -1, -1, -0.4472136},
        new double[]{-1, -1, 1, -0.4472136},
        new double[]{0, 0, 0, 1.78885438},
    };
    public static readonly int[][] edges = {
        new int[]{0, 1},
        new int[]{0, 2},
        new int[]{0, 3},
        new int[]{0, 4},
        new int[]{1, 2},
        new int[]{1, 3},
        new int[]{1, 4},
        new int[]{2, 3},
        new int[]{2, 4},
        new int[]{3, 4},
    };
    public static readonly int[][][] cells = {
        new int[][] {
            new int[]{0, 2, 3, 4},
        },
        new int[][] {
            new int[]{0, 1, 2, 4},
        },
        new int[][] {
            new int[]{4, 2, 3, 1},
        },
        new int[][] {
            new int[]{4, 1, 3, 0},
        },
        new int[][] {
            new int[]{3, 1, 2, 0},
        },
    };
    public static readonly double[][] normals = {
        new double[]{0.55901699, -0.55901699, 0.55901699, 0.25},
        new double[]{0.55901699, 0.55901699, -0.55901699, 0.25},
        new double[]{-0.55901699, -0.55901699, -0.55901699, 0.25},
        new double[]{-0.55901699, 0.55901699, 0.55901699, 0.25},
        new double[]{-0, -0, -0, -1},
    };
}
